server:
  port: 8081

spring:
  application:
    name: auth-service

  sql:
    init:
      continue-on-error: false

  datasource:
    # url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bankdb}
    # url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSL_MODE:require}
    # url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?ssl=true&sslmode=verify-full&sslfactory=org.postgresql.ssl.DefaultJavaSSLFactory
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require
    # username: ${SPRING_DATASOURCE_USERNAME:bankuser}
    username: ${DB_USER}
    # password: ${SPRING_DATASOURCE_PASSWORD:bankpass}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
      initialization-fail-timeout: 60000
      keepalive-time: 30000
      max-lifetime: 1800000
      connection-test-query: SELECT 1

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:redispass}

jwt:
  secret: ${JWT_SECRET:supersecretjwtkey2024bankingsystem}
  expiration: 86400000

google:
  client-id: ${GOOGLE_CLIENT_ID:your-google-client-id.apps.googleusercontent.com}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
