name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-south-1

      - name: Get EC2 instances in ASG
        id: get-instances
        run: |
          INSTANCE_IDS=$(aws autoscaling describe-auto-scaling-groups \
            --auto-scaling-group-names cloudbank-asg \
            --query "AutoScalingGroups[0].Instances[*].InstanceId" \
            --output text)

          IPS=$(aws ec2 describe-instances \
            --instance-ids $INSTANCE_IDS \
            --query "Reservations[*].Instances[*].PublicIpAddress" \
            --output text)

          echo "ips=$IPS" >> $GITHUB_OUTPUT
          
      - name: Deploy to all instances
        run: |
          for ip in ${{ steps.get-instances.outputs.ips }}
          do
            echo "Deploying to $ip"
            echo "${{ secrets.EC2_KEY }}" > key.pem
            chmod 600 key.pem
            ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@$ip "
              cd /home/ec2-user/cloudbank              
              export GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
              export GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
              git pull              
              docker-compose down              
              docker-compose up -d --build              
              sleep 20           
              # ensure frontend is up
              docker-compose up -d frontend              
              sleep 10              
              # restart gateway after frontend is ready
              docker-compose restart api-gateway
              docker ps
              echo "done"
            "
          done
